# Generated by Django 5.2.7 on 2025-11-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersTable',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(default='emp@org.com', max_length=50)),
                ('user_mob', models.CharField(max_length=10, unique=True)),
                ('profile_pic', models.URLField(default='empty')),
            ],
        ),
    ]
